### ISSUE TITLE
Adding new users does not work reliably

### ISSUE THREAD

**Issue by eneesolutions** [rowyio/rowy#578]
I have added one user our Rowy instance and it worked, but after that another email address wouldn't work.

What happens is the invite email gets sent, I can click get started from the email and sign in with Google, but there are no tables or logged in user shown. I tried logging out and logging back in, but the user screen was broken.

Also the new user didn't show in the user_management collection at all.

Lastly from a UI perspective, I think when you add a user, it should show as pending accept so you can see it worked and potentially precreate the user in the collection? Just an idea.

Thanks

**Comment by notsidney** [comment]
Hi, did you make sure to set the user roles when inviting first?

**Comment by eneesolutions** [comment]
Yep, I set them both to the same role, one added, the other didn't

**Comment by eneesolutions** [comment]
I have some further info on this if it's helpful. I added a few more users recently and when I set them to the built-in 'ADMIN' role, it actually added the users. Then after they were in the system I was able to switch them over to just being a 'USER' which was the role I created. 

Another part is every time I add a user, they initially show as having no roles, rather than the one I set. I can then set a role and it sticks from then on.

**Comment by harinij** [comment]
Closing old issue, as this has been fixed in the latest release.

**Comment by Labeuran** [comment]
I still face the same issue, my invites do not arrive at the email addresses I send them to.

**Comment by harinij** [comment]
@Labeuran Is the user receiving the email on the promotions tab? Also, the invites take the user to [https://rowy.app/](https://rowy.app/) where if they sign in they can see all the invites received on that email.
